spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: phantom
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  data:
    rest:
      basePath: /datarest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  health:
    defaults:
      enabled: true